# Global settings
splash = false

# Preload
preload = /home/za66e/Pictures/wallpapers/*
 
# Monitor specific block
wallpaper {
    monitor = eDP-1
    path = /home/za66e/Pictures/wallpapers/*
    fit_mode = cover
}
